# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'
Vagrant.require_version '>= 1.8.1'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty32"
    config.vm.hostname = "d8-vagrant"

    # Create a forwarded port mapping which allows access to a specific port
    config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true # website (accessing "localhost:8080")
    config.vm.network :forwarded_port, guest: 443, host: 8443, auto_correct: true # ssl (accessing "localhost:8443")
    config.vm.network :forwarded_port, guest: 3306, host: 4306, auto_correct: true # mysql
    config.vm.network :forwarded_port, guest: 9000, host: 9090, auto_correct: true # xdebug

    config.vm.synced_folder "./", "/vagrant", id: "vagrant", :mount_options => ["dmode=775", "fmode=775"]

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.customize ['modifyvm', :id, '--memory', '1024']
        vb.customize ["modifyvm", :id, "--cpus", "1"]
     end

    config.vm.provision :shell, :path => "bootstrap.sh", :args => []

end
